// calculate the number of resources generated by a tile by tile level
pub fn calculate_resources_per_cycle(level: u8) -> u64 {
    ((2 * level) as u64) + ((10 * level) as u64)
}

pub fn calculate_max_capacity(level: u8, cycles_per_period: i32) -> u64 {
    // resource calculation per cycle
    let resources_per_cycle = calculate_resources_per_cycle(level);

    resources_per_cycle * cycles_per_period as u64
}